### ISSUE TITLE
Really Confused with Mouse positioning!

### ISSUE THREAD

**Issue by AmazingGamerBoy** [pulviscriptor/agario-client#109] opened 2016-03-17 08:30 UTC
This includes agario-client so please do not close.
People have been saying that positioning has changed a while ago. Can someone please help with getting my ball that I control position in the map? Like how do I get the mouseX and mouseY things now? Please help I'm pretty new to this!

**Comment by AmazingGamerBoy** [comment] 2016-03-17 08:31
I want a userscript to steam the positioning of my ball to my server using agaric-client, but that doesn't matter, its just the way to find x and y.

**Comment by MasonBurdette** [comment] 2016-03-17 13:12
The problem is figuring out the offset.  It's easy once you figure it out.

**Comment by Juampab12** [comment] 2016-03-17 13:21
I´ve tried using a chrome extension using socket io, but the server crashes on launch. I´m not able to see if it works or not please help me, I have crated another thread. If you help me fix it i will tell u my method if it works...

**Comment by pulviscriptor** [comment] 2016-04-07 21:03
@AmazingGamerBoy
>This includes agario-client so please do not close.

20 days passed, can we close it now?

**Comment by AmazingGamerBoy** [comment] 2016-04-07 23:22
Yes u could have ages ago

**Comment by pulviscriptor** [comment] 2016-04-08 06:13
@AmazingGamerBoy 
You're owner of issue, you have button "Close" when issue is solved for you, so next time it would be nice to close your issue yourself when its solved.

**Closed by pulviscriptor** 2016-04-08 06:13 UTC

**Comment by AmazingGamerBoy** [comment] 2016-04-08 07:41
kk
