### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Petterholm** [pulviscriptor/agario-client#73] opened 2016-01-28 14:01 UTC
I get an error when running a bot script it looks like a agario-client error
https://gyazo.com/7979b459a50db12e0befe84d455395c0

**Comment by pulviscriptor** [comment] 2016-01-28 15:35
If you use SOCKS you need to add `on.packetError` listener and `preventCrash()` in it https://github.com/pulviscriptor/agario-client/issues/46#issuecomment-169786276
Also you need manually to fix `ws` crashes until in get fixed in repo https://github.com/websockets/ws/issues/669
All these problems because buggy public SOCKS servers that breaks packets and sends random data sometimes.

**Comment by Petterholm** [comment] 2016-01-28 15:37
i dont use socks proxies

**Comment by pulviscriptor** [comment] 2016-01-28 15:44
Okay, then we have a problem.
How often you see those crashes and what version of `agario-client` you have? You can check it in `npm list`

**Comment by Petterholm** [comment] 2016-01-29 13:18
I see them after running my bots maybe 2 to 3 minutes.
https://gyazo.com/81602225ef87e94d6421a3829475b808

**Comment by pulviscriptor** [comment] 2016-01-29 14:25
I can not reproduce it so i need that broken packet from you.
Do something like 
```javascript
client.on('packetError', function(packet) {
   console.log('Report this packet: ' + packet.toString());
});
```
After that you will see packet in console, bring it here so i can look at it.

**Comment by Petterholm** [comment] 2016-01-29 14:26
where am i supposed to write that?

**Comment by pulviscriptor** [comment] 2016-01-29 14:27
Where you have all your events attached, attach this one too.

**Comment by Petterholm** [comment] 2016-01-29 14:27
where do i have that?

**Comment by Petterholm** [comment] 2016-01-29 14:29
in node-modules?

**Comment by pulviscriptor** [comment] 2016-01-29 14:32
@Petterholm
Uhm... Did you made your bot yourself?
If not, you probably should ask help from guy who gave you your bot. Tell him to attach that event.

**Comment by Petterholm** [comment] 2016-01-29 14:34
https://github.com/davidmann4/agario-feeder-bot/blob/master/feeder.js

**Comment by pulviscriptor** [comment] 2016-01-29 14:39
@Petterholm
Are you sure you do not using SOCKS/proxy? I see that bot is supporting it.

**Comment by Petterholm** [comment] 2016-01-29 14:40
i use these bots https://neu1-api.asm.skype.com/v1/objects/0-neu-d2-a734a0e9d6ffb67aae12852662dfc3f8/views/original

**Comment by Petterholm** [comment] 2016-01-29 14:42
proxies*

**Comment by Petterholm** [comment] 2016-01-29 14:42
do socks crash it?

**Comment by pulviscriptor** [comment] 2016-01-29 14:42
>do socks crash it?

**Comment by pulviscriptor** [comment] 2016-01-29 14:44
Go there https://github.com/davidmann4/agario-feeder-bot/issues and create issue about bad socks breaking packets.
You can refer my investigation https://github.com/pulviscriptor/agario-client/issues/56#issuecomment-171772427
Authors of that bot need to add `on.packetError` and do `preventCrash()`

**Comment by Petterholm** [comment] 2016-01-29 14:46
could you make it? i dont really understand what i am supposed to write

**Comment by pulviscriptor** [comment] 2016-01-29 14:48
Sure. I will create it.

**Comment by Petterholm** [comment] 2016-01-29 14:48
thx

**Closed by pulviscriptor** 2016-01-29 14:48 UTC

**Comment by pulviscriptor** [comment] 2016-01-30 00:41
@Petterholm
We need your help.
@WJKH in issue in`agario-feeder-bot` told me that bot supports only proxy without SOCKS, so i need to see your packets to check if proxy have same issues as SOCKS or there is bug in `agario-client`.
Open locally this file https://github.com/davidmann4/agario-feeder-bot/blob/master/feeder.js#L66 and replace
```javascript
        bot.client.on('connectionError', function(e) {
            if (config.verbosityLevel > 0) {
                bot.log('Connection Failed: ' + e);
            }
        });


        bot.client.on('myNewBall', function(ball_id) {
            // Should always be generated.
            if (config.verbosityLevel > -1) {
                bot.log('New Cell Generated (' + ball_id + ')');
            }
        });
```
with
```javascript
        bot.client.on('connectionError', function(e) {
            if (config.verbosityLevel > 0) {
                bot.log('Connection Failed: ' + e);
            }
        });

bot.client.on('packetError', function(packet) {
   console.log('Report this packet: ' + packet.toString());
});

        bot.client.on('myNewBall', function(ball_id) {
            // Should always be generated.
            if (config.verbosityLevel > -1) {
                bot.log('New Cell Generated (' + ball_id + ')');
            }
        });
```
On crash you will see packet that caused crash, post it here. Better to post 3-6 packets.
Thank you.

**Comment by Petterholm** [comment] 2016-01-30 07:02
I will do it in 1-2 hours

Sendt fra min iPhone

**Comment by Petterholm** [comment] 2016-01-30 08:51
https://gyazo.com/5cbfa9eeb2fc59d5831fc28fe6a92985

**Comment by pulviscriptor** [comment] 2016-01-30 17:15
@Petterholm 
Can you report more packets and copy/paste them as text please?
Like this: 10 E7 FB FF FF F0 FC FF FF 00 00 00 00

**Comment by Petterholm** [comment] 2016-01-30 17:21
I will do it soon

Den lørdag 30. januar 2016 skrev pulviscriptor <notifications@github.com>
følgende:

**Comment by Petterholm** [comment] 2016-01-30 17:45
How can i get more?

Sendt fra min iPhone

**Comment by pulviscriptor** [comment] 2016-01-30 17:50
@Petterholm
Just run it again and you get new packet. Repeat it few times.
