### ISSUE TITLE
Packet Errors

### ISSUE THREAD

**Issue by DaAwesomeRazor** [pulviscriptor/agario-client#56] opened 2016-01-14 17:50 UTC
when i run 70 132 mass bots this is the packet error i get

Packet error detected for packet: 10 0c 00 a5 88 28 00 e2 a7 29 00 5c d5 28 00 8d a5 29 00 59 a9 29 00 e5 a2 29 00 f1 57 29 00 ef a8 29 00 e5 97 29 00 80 a7 29 00 ca 87 00 00 00 47 a6 29 00 71 0b 00 00 3b ec ff ff 39 00 07 ff 71 00 00 00 4d a6 29 00 cd 0e 00 00 bc e9 ff ff 72 00 fe ff 07 00 00 00 00 a7 29 00 3c 0e 00 00 8e f0 ff ff 20 00 07 79 ff 00 00 00 d0 a7 29 00 56 05 00 00 e9 ec ff ff 0b 00 74 ff 07 00 00 00 e1 a7 29 00 9e fe ff ff a1 ed ff ff f6 04 20 07 ff 00 00 00 f9 a7 29 00 ee 08 00 00 c6 ed ff ff 39 00 07 ff 71 00 00 00 fa a7 29 00 5c 09 00 00 3a ee ff ff 39 00 07 ff 71 00 00 00 fb a7 29 00 e8 08 00 00 3a ee ff ff 39 00 07 ff 71 00 00 00 3a a8 29 00 e3 0d 00 00 c9 eb ff ff 43 00 ff 07 9c 00 00 00 00 00 00 00 02 00 00 00 29 90 29 00 22 94 29 00 82 7e 01 97 10 0c 00 45 a7 29 00 85 9d 29 00 f1 57 29 00 f3 a8 29 00 75 5a 29 00 db 9b 29 00 97 8a 29 00 88 a2 29 00 78 71 29 00 67 a5 29 00 86 94 29 00 78 a9 29 00 86 94 29 00 7b a9 29 00 5a 9c 29 00 7a a9 29 00 3d 1f 29 00 6f a9 29 00 3d 1f 29 00 6e a9 29 00 3d 1f 29 00 70 a9 29 00 1b a4 29 00 33 a8 29 00 5c d5 28 00 b8 07 00 00 5f f2 ff ff b6 02 07 ff df 00 00 00 c1 68 29 00 ca 07 00 00 0e ec ff ff 8f 00 82 07 ff 00 00 00 26 8e 29 00 8a 06 00 00 12 ee ff ff ec 00 76 07 ff 00 00 00 c6 9c 29 00 6f 0d 00 00 fe f0 ff ff 74 00 54 07 ff 00 00 00 5d 9d 29 00 38 08 00 00
35 says: Crash will be prevented, bot will be disconnected
C

This really needs to get fixed because it happens all the time. I think its internet because it doesnt happen when I run it on vps

**Comment by pulviscriptor** [comment] 2016-01-14 18:22
@DaAwesomeRazor
While i porting code of agar for test, can you tell 
- what `Node.js` version you use
- what OS
- do you use SOCKS
- show `npm list` output

**Comment by DaAwesomeRazor** [comment] 2016-01-14 19:39
Ok im also getting this error
@pulviscriptor 
buffer.js:582
    throw new RangeError('Trying to access beyond buffer length');
    ^
RangeError: Trying to access beyond buffer length
    at checkOffset (buffer.js:582:11)
    at Buffer.readUInt8 (buffer.js:588:5)
    at Object.Packet.readUInt8 (/opt/razor.secureobscure.com/bots/packet.js:25:29)
    at Client.processors.16 (/opt/razor.secureobscure.com/bots/agario-client.js:242:43)
    at Object.Client.onMessage (/opt/razor.secureobscure.com/bots/agario-client.js:137:9)
    at WebSocket.onMessage (/opt/razor.secureobscure.com/node_modules/ws/lib/WebSocket.js:418:14)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.onbinary (/opt/razor.secureobscure.com/node_modules/ws/lib/WebSocket.js:823:10)
    at /opt/razor.secureobscure.com/node_modules/ws/lib/Receiver.js:537:18
    at Receiver.applyExtensions (/opt/razor.secureobscure.com/node_modules/ws/lib/Receiver.js:364:5)
    at /opt/razor.secureobscure.com/node_modules/ws/lib/Receiver.js:531:14

**Comment by DaAwesomeRazor** [comment] 2016-01-14 19:40
Also im using the latest nodejs
windows for the first error and ubuntu for the second i just posted
I do use socks



NPM LIST:



agario-client@1.1.8 C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL
├── cli-clear@1.0.4 extraneous
├── express@4.13.3 extraneous
├── http@0.0.0 extraneous
├── http-proxy@1.12.0 extraneous
├── is-json@1.2.5 extraneous
├── nodejs-websocket@1.4.1 extraneous
├── readline-sync@1.2.21 extraneous
├── socks@1.1.8 extraneous
└─┬ ws@0.7.2
  ├─┬ bufferutil@1.1.0
  │ ├── bindings@1.2.1
  │ └── nan@1.8.4
  ├── options@0.0.6
  ├── ultron@1.0.2
  └─┬ utf-8-validate@1.1.0
    ├── bindings@1.2.1
    └── nan@1.8.4

npm ERR! extraneous: cli-clear@1.0.4 C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\cli-clear
npm ERR! extraneous: express@4.13.3 C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\express
npm ERR! extraneous: http@0.0.0 C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\http
npm ERR! extraneous: http-proxy@1.12.0 C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\http-proxy
npm ERR! extraneous: is-json@1.2.5 C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\is-json
npm ERR! extraneous: nodejs-websocket@1.4.1 C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\nodejs-websocket
npm ERR! extraneous: readline-sync@1.2.21 C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\readline-sync
npm ERR! extraneous: socks@1.1.8 C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\socks

**Comment by pulviscriptor** [comment] 2016-01-14 20:15
@DaAwesomeRazor 
While i'm writing my investigation here, try to update `ws` to latest. You can do `npm update` to update outdated `agario-client` too. But that packet from first message is corrupted, so outdated `agario-client` is not the reason. But it may fix second message (about crash).
Lets see if updating `ws` will fix anything. Do `npm update`

**Comment by pulviscriptor** [comment] 2016-01-14 20:37
## Investigation results ##
Ported only first part (packet ID 16 part 1)
agar.io: http://pastebin.com/raw/vwSm5Tx3  (code used http://pastebin.com/raw/C4xSJDwy )
Simulation on `agario-client`: http://pastebin.com/raw/i5GZUb8N (code used http://pastebin.com/raw/Xy5YGQhx ) (first byte removed since its ID)
IDs are the same. No bugs in code.
But you got very cool packet. There is 12 eating events (`eaters_count=12`) that have very simple structure
```javascript
//reading eat events
for(var i=0;i<eaters_count;i++) {
	var eater_id = packet.readUInt32LE(); //<-- reading 4 bytes
	var eaten_id = packet.readUInt32LE(); //<-- reading 4 bytes
									      // NO MORE READING AT ALL!
    ...
``` 
and problem is somewhere between 5 and 6 and we see that valid IDs starting with `26` and `27`
Adding bytes gave nothing.
I even went to bits level.
Converting http://pastebin.com/raw/e17TJYZE
Testing http://pastebin.com/raw/JSx19EBe
Shows same broken IDs without changes. 
And you know what? Adding/removing bits gave nothing.
Who wants to try himself, add/remove bits like this http://pastebin.com/raw/QMXPyugs 
Adding/removing 32 bits should be enough for bruteforcing all possibilities since we bruteforcing one `readUInt32LE()` call.
And i tried to get any strings from data http://pastebin.com/raw/ypfdzEw9 (via adding bits) and i did not got any strings/nicknames.

No valid IDs, no strings, no nothing. I don't understand where that data came from and how it get stuck inside packet.

**Comment by DaAwesomeRazor** [comment] 2016-01-14 20:50
Ok still getting error, even though I updated the websocket

**Comment by pulviscriptor** [comment] 2016-01-14 20:52
Is it error "`Packet error detected for packet`" or "`throw new RangeError('Trying to access beyond buffer length');`"?

**Comment by DaAwesomeRazor** [comment] 2016-01-14 21:47
throw new RangeError('Trying to access beyond buffer length

**Comment by DeepSnowNeeL** [comment] 2016-01-14 23:24
Told you guys, it's packet de-sync. It looks like socks lib or nodejs can't
handle too much packets without desync sometimes. Remember node.js is
monothread so if it uses ~15% of a 8 core computer, it is already at max
cpu and can't keep up with the number of packets incomming from many bots.

Le jeu. 14 janv. 2016 22:47, DaAwesomeRazor <notifications@github.com> a
écrit :

**Comment by DaAwesomeRazor** [comment] 2016-01-15 01:30
@DeepSnowNeeL Yeah its probably socks because i can run that many bots using localAddress and its fine

**Comment by DaAwesomeRazor** [comment] 2016-01-15 03:21
@pulviscriptor This needs to be fixed because I cant run my bots without being crashed every 5 minutes

**Comment by pulviscriptor** [comment] 2016-01-15 07:44
@DeepSnowNeeL
I am sure its not Node.js
Its that `socks` lib, or `ws` lib, or SOCKS servers by themselves, or my code somewhere, or maybe agar.io sending some garbage sometimes, who knows.
@DaAwesomeRazor 
>being crashed every 5 minutes

Are you using `on.packetError(packet, err, preventCrash)` and still getting crash? 

Since you have stable crashes, can i ask you try other SOCKS agents? You can google "node.js socks agent" and try some other lib than `socks` from there.
If its too hard for you to code, i can write code for you.

**Comment by pulviscriptor** [comment] 2016-01-15 07:57
@DaAwesomeRazor
Wait, i decided to find whats wrong myself. I will write what i found here.
I may ask you for some details later.

**Comment by pulviscriptor** [comment] 2016-01-15 15:20
After few hours having fun and dominating with bots i can say, `ws` is crashing like crazy.
I will look what i can do with it, but now at least i can reproduce issue.

**Comment by DaAwesomeRazor** [comment] 2016-01-15 17:06
Can I send you my script? and you tell me whats wrong? My script crashes a ton. When i updated ws it stopped the index out of range thing. But im still getting the buffer length. Im 95% sure its Socks5 because when I use localAddress it works fine. But localAddress is a pain in the ass so..

**Comment by harrydevelop** [comment] 2016-01-15 17:23
@DaAwesomeRazor hei can i send you a script maybe its yours but it work great ,there are only one problem with this websocket ws://razor.secureobscure.com:6578

**Comment by pulviscriptor** [comment] 2016-01-15 17:34
@DaAwesomeRazor 
I can reproduce your problem. I also think there is memory leak, and i need some time to find whats wrong.
But first i want to play with bots little more  :yum:

**Comment by harrydevelop** [comment] 2016-01-15 17:40
@pulviscriptor can i try it?

**Comment by DaAwesomeRazor** [comment] 2016-01-15 17:49
@pulviscriptor I think It is a problem with wifi. Something that the packets arent being sent on time. I dont get as many errors on my vpns, but when i use crappy internet the problems start.

**Comment by DaAwesomeRazor** [comment] 2016-01-15 17:50
@harrydevelop Thats my script... It wont help me I already know what it does..

**Comment by pulviscriptor** [comment] 2016-01-15 17:55
@harrydevelop
Sure, give me your skype.

**Comment by pulviscriptor** [comment] 2016-01-15 17:58
@DaAwesomeRazor 
You can add `try catch` block in WebSocket.js for code that crashes for temporary fix.
For example this one of crashes `WebSocket.js` line 425
```javascript
  function onError (event) {
    event.type = 'error';
    event.target = target;
    listener.call(target, event);
  }
```
do it
```javascript
  function onError (event) {
   try {
    event.type = 'error';
    event.target = target;
   }catch(e){
    //we don't care
   }
   listener.call(target, event);
  }
```
And fix all those crashes. It will work as temporary solution.

**Comment by harrydevelop** [comment] 2016-01-15 17:59
@DaAwesomeRazor nice work...are you tried to use ethernet connection?
@pulviscriptor thanks if you need something i can help you doing computer engineering 
skype : harry16ita with memes pic

**Comment by DaAwesomeRazor** [comment] 2016-01-15 18:47
@pulviscriptor  K I will try that

**Comment by harrydevelop** [comment] 2016-01-15 18:50
@DaAwesomeRazor if it dosent work i can ask to my university professor ,tell you tomorrow what is wrong :)

**Comment by DaAwesomeRazor** [comment] 2016-01-15 18:52
@pulviscriptor  vent.target = target;
                 ^

TypeError: Cannot assign to read only property 'target' of reserved fields must be empty
    at WebSocket.onError (C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\ws\lib\WebSocket.js:422:18)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onerror (C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\ws\lib\WebSocket.js:832:10)
    at Receiver.error (C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\ws\lib\Receiver.js:317:8)
    at Receiver.processPacket (C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\ws\lib\Receiver.js:191:12)
    at Receiver.add (C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\ws\lib\Receiver.js:91:24)
    at Socket.firstHandler (C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\ws\lib\WebSocket.js:774:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)


Thats another error im getting, but I havent tried the try and catch thing yet so imma try that quicly

**Comment by DaAwesomeRazor** [comment] 2016-01-15 19:02
Ok now im getting this error,. I replaced the on error thing and now im getting this.



else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\ws\lib\WebSocket.js:214:16)
    at Object.Client.send (C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\agario-client.js:177:17)
    at Object.Client.onConnect (C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\agario-client.js:90:14)
    at WebSocket.onOpen (C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\ws\lib\WebSocket.js:432:14)
    at emitNone (events.js:67:13)
    at WebSocket.emit (events.js:166:7)
    at WebSocket.establishConnection (C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\ws\lib\WebSocket.js:848:8)
    at ClientRequest.upgrade (C:\Users\shzd1\Desktop\RSAgarBotz Version 1 REAL\node_modules\ws\lib\WebSocket.js:738:25)
    at ClientRequest.g (events.js:260:16)
    at emitThree (events.js:97:13)
    at ClientRequest.emit (events.js:175:7)

**Comment by pulviscriptor** [comment] 2016-01-15 19:03
@DaAwesomeRazor 
Do `try catch` on them all. And again, its temporary solution.

**Comment by DaAwesomeRazor** [comment] 2016-01-15 23:26
@pulviscriptor  You think because im just using a lot of bots and really crappy socks proxies?

**Comment by Sonicmaster13** [comment] 2016-01-15 23:53
try {} catch(e) {} wont work. We tried it, and no matter what we still keep getting errors like: 

    event.target = target;
                 ^

    TypeError: Cannot assign to read only property 'target' of reserved fields must be empty
    at WebSocket.onError (C:\Users\clock\Desktop\RSBotz\node_modules\ws\lib\WebSocket.js:422:18)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onerror (C:\Users\clock\Desktop\RSBotz\node_modules\ws\lib\WebSocket.js:832:10)
    at Receiver.error (C:\Users\clock\Desktop\RSBotz\node_modules\ws\lib\Receiver.js:317:8)
    at Receiver.processPacket (C:\Users\clock\Desktop\RSBotz\node_modules\ws\lib\Receiver.js:191:12)
    at Receiver.add (C:\Users\clock\Desktop\RSBotz\node_modules\ws\lib\Receiver.js:91:24)
    at Socket.firstHandler (C:\Users\clock\Desktop\RSBotz\node_modules\ws\lib\WebSocket.js:774:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

**Comment by pulviscriptor** [comment] 2016-01-16 07:34
>You think because im just using a lot of bots and really crappy socks proxies?

Here what i can say for you.
I use this code
```javascript
var last_interval = (+new Date);

setInterval(function(){
    var now = (+new Date);
    console.log('delay: ' + (now-last_interval-interval) + 'ms');
    last_interval = now;
}, 100);
```
When delay reaches <b>OVER 250 MILLISECONDS</b> `ws` crashes. I was able to get delays <b>over 1000ms</b> for one run. Its crazy.
And even if you start fixed amount of bots, first delays will be 0-1ms, but will slowly increasing. So i think there is memory leak.
I will investigate more, if this is problem in `ws` i will create issue there.

>try {} catch(e) {} wont work. We tried it, and no matter what we still keep getting errors

It will work. You just getting new errors over and over again. I do not how much there places in code that causes crash.
You can keep adding `try catch` or wait for my solution, which i don't know at the moment.

**Comment by DaAwesomeRazor** [comment] 2016-01-16 16:49
@pulviscriptor  Ok so we saw that in the websocket code that there was throw new error. We replaced that with a console.log('websocket error!') so I dont think there are any more errors. I havent got any in a while.

**Comment by pulviscriptor** [comment] 2016-01-23 04:44
Lets keep it open until `ws` gets fixed so peoples can see how to fix it until then.

**Comment by DaAwesomeRazor** [comment] 2016-01-23 21:28
@pulviscriptor  K

**Comment by DaAwesomeRazor** [comment] 2016-01-31 17:16
Just started using a new socks proxy list. Im already getting less packet errors

**Closed** 2016-04-22 10:02 UTC

**Comment by pulviscriptor** [comment] 2016-04-22 10:04
`ws` finally got updated `npm` package. No more manual patching required, upgrade your `agario-client` to 1.3.6
